In [3]:
import pandas as pd
df = pd.read_csv("/content/sample_data/heart_disease_uci.csv")
df

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,916,54,Female,VA Long Beach,asymptomatic,127.0,333.0,True,st-t abnormality,154.0,False,0.0,NaN,NaN,NaN,1
916,917,62,Male,VA Long Beach,typical angina,NaN,139.0,False,st-t abnormality,NaN,NaN,NaN,NaN,NaN,NaN,0
917,918,55,Male,VA Long Beach,asymptomatic,122.0,223.0,True,st-t abnormality,100.0,False,0.0,NaN,NaN,fixed defect,2
918,919,58,Male,VA Long Beach,asymptomatic,NaN,385.0,True,lv hypertrophy,NaN,NaN,NaN,NaN,NaN,NaN,0
919,920,62,Male,VA Long Beach,atypical angina,120.0,254.0,False,lv hypertrophy,93.0,True,0.0,NaN,NaN,NaN,1

In [4]:
df.head()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [5]:
df.tail()

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
915,916,54,Female,VA Long Beach,asymptomatic,127.0,333.0,True,st-t abnormality,154.0,False,0.0,NaN,NaN,NaN,1
916,917,62,Male,VA Long Beach,typical angina,NaN,139.0,False,st-t abnormality,NaN,NaN,NaN,NaN,NaN,NaN,0
917,918,55,Male,VA Long Beach,asymptomatic,122.0,223.0,True,st-t abnormality,100.0,False,0.0,NaN,NaN,fixed defect,2
918,919,58,Male,VA Long Beach,asymptomatic,NaN,385.0,True,lv hypertrophy,NaN,NaN,NaN,NaN,NaN,NaN,0
919,920,62,Male,VA Long Beach,atypical angina,120.0,254.0,False,lv hypertrophy,93.0,True,0.0,NaN,NaN,NaN,1

In [6]:
df.isnull().sum()

id            0
age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
num           0
dtype: int64

In [7]:
df.dtypes

id            int64
age           int64
sex          object
dataset      object
cp           object
trestbps    float64
chol        float64
fbs          object
restecg      object
thalch      float64
exang        object
oldpeak     float64
slope        object
ca          float64
thal         object
num           int64
dtype: object

In [8]:
# Numerical features
numerical_features = df.select_dtypes(include=['int64', 'float64']).columns
print(f"Numerical Features:, {numerical_features}")

# Categorical features
categorical_features = df.select_dtypes(include=['object', 'category']).columns
print(f"Categorical Features:, {categorical_features}")

Numerical Features:, Index(['id', 'age', 'trestbps', 'chol', 'thalch', 'oldpeak', 'ca', 'num'], dtype='object')
Categorical Features:, Index(['sex', 'dataset', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'thal'], dtype='object')

In [9]:
##### Imputing columns with less missing values

# Imputing numerical col
for col in ['trestbps', 'chol', 'thalch', 'oldpeak']:
    df[col].fillna(df[col].mean(), inplace=True)

# Imputing categorical columns
for col in ['fbs', 'restecg', 'exang']:
    df[col].fillna(df[col].mode()[0], inplace=True)


# Note: we are not imputing that and ca col here.
# because it is mentioned in the 2nd part.
# So, I impute these 2 columns there.

<ipython-input-9-cde4eade83fb>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)
<ipython-input-9-cde4eade83fb>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
<ipython-input-9-cde4eade83fb>:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col].fillna(df[col].mode()[0], inplace=True)

In [10]:
# droping the columns with high missing values (slope, ca and thal):

df.drop(columns=['slope'], inplace=True)

In [11]:
for column in ['thal', 'ca']:
    df[column].fillna(df[column].mode()[0], inplace=True)

<ipython-input-11-66b4fd118b22>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].mode()[0], inplace=True)

In [12]:
print(df.isnull().sum())

# Now, thal and ca column has no null values.

id          0
age         0
sex         0
dataset     0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalch      0
exang       0
oldpeak     0
ca          0
thal        0
num         0
dtype: int64

In [13]:
def age_group(age):
    if age<40:
        return ("<40")
    elif 40<= age <=60:
        return ("40-60")
    else:
        return (">60")

In [14]:
df["age_group"] = df["age"].apply(age_group)
df

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,ca,thal,num,age_group
0,1,63,Male,Cleveland,typical angina,145.000000,233.0,True,lv hypertrophy,150.000000,False,2.300000,0.0,fixed defect,0,>60
1,2,67,Male,Cleveland,asymptomatic,160.000000,286.0,False,lv hypertrophy,108.000000,True,1.500000,3.0,normal,2,>60
2,3,67,Male,Cleveland,asymptomatic,120.000000,229.0,False,lv hypertrophy,129.000000,True,2.600000,2.0,reversable defect,1,>60
3,4,37,Male,Cleveland,non-anginal,130.000000,250.0,False,normal,187.000000,False,3.500000,0.0,normal,0,<40
4,5,41,Female,Cleveland,atypical angina,130.000000,204.0,False,lv hypertrophy,172.000000,False,1.400000,0.0,normal,0,40-60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,916,54,Female,VA Long Beach,asymptomatic,127.000000,333.0,True,st-t abnormality,154.000000,False,0.000000,0.0,normal,1,40-60
916,917,62,Male,VA Long Beach,typical angina,132.132404,139.0,False,st-t abnormality,137.545665,False,0.878788,0.0,normal,0,>60
917,918,55,Male,VA Long Beach,asymptomatic,122.000000,223.0,True,st-t abnormality,100.000000,False,0.000000,0.0,fixed defect,2,40-60
918,919,58,Male,VA Long Beach,asymptomatic,132.132404,385.0,True,lv hypertrophy,137.545665,False,0.878788,0.0,normal,0,40-60
919,920,62,Male,VA Long Beach,atypical angina,120.000000,254.0,False,lv hypertrophy,93.000000,True,0.000000,0.0,normal,1,>60

In [15]:
# min_chol = df['chol'].min()
# mid_chol = (df['chol'].max() - df['chol'].min())/2
# max_chol = df['chol'].max()

# print(f"min_chol: {min_chol}")
# print(f"mid_chol: {mid_chol}")
# print(f"max_chol: {max_chol}")

In [16]:
def chol_types(chol):
    if chol < 200:
        return "Low"
    elif 200 <= chol <= 239:
        return "Medium"
    else:
        return "High"

In [17]:
df["chol_types"] = df["chol"].apply(chol_types)
df

# Note:Its very important to use return instead of print in function. when we use .apply()
# other wise the function values not showing in the dataframe.

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,ca,thal,num,age_group,chol_types
0,1,63,Male,Cleveland,typical angina,145.000000,233.0,True,lv hypertrophy,150.000000,False,2.300000,0.0,fixed defect,0,>60,Medium
1,2,67,Male,Cleveland,asymptomatic,160.000000,286.0,False,lv hypertrophy,108.000000,True,1.500000,3.0,normal,2,>60,High
2,3,67,Male,Cleveland,asymptomatic,120.000000,229.0,False,lv hypertrophy,129.000000,True,2.600000,2.0,reversable defect,1,>60,Medium
3,4,37,Male,Cleveland,non-anginal,130.000000,250.0,False,normal,187.000000,False,3.500000,0.0,normal,0,<40,High
4,5,41,Female,Cleveland,atypical angina,130.000000,204.0,False,lv hypertrophy,172.000000,False,1.400000,0.0,normal,0,40-60,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,916,54,Female,VA Long Beach,asymptomatic,127.000000,333.0,True,st-t abnormality,154.000000,False,0.000000,0.0,normal,1,40-60,High
916,917,62,Male,VA Long Beach,typical angina,132.132404,139.0,False,st-t abnormality,137.545665,False,0.878788,0.0,normal,0,>60,Low
917,918,55,Male,VA Long Beach,asymptomatic,122.000000,223.0,True,st-t abnormality,100.000000,False,0.000000,0.0,fixed defect,2,40-60,Medium
918,919,58,Male,VA Long Beach,asymptomatic,132.132404,385.0,True,lv hypertrophy,137.545665,False,0.878788,0.0,normal,0,40-60,High
919,920,62,Male,VA Long Beach,atypical angina,120.000000,254.0,False,lv hypertrophy,93.000000,True,0.000000,0.0,normal,1,>60,High

In [18]:
# Create binary feature 'IsRisk'
df['IsRisk'] = ((df['chol'] > 240) & (df['trestbps'] > 140) & (df['age'] > 60)).astype(int)
df

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,ca,thal,num,age_group,chol_types,IsRisk
0,1,63,Male,Cleveland,typical angina,145.000000,233.0,True,lv hypertrophy,150.000000,False,2.300000,0.0,fixed defect,0,>60,Medium,0
1,2,67,Male,Cleveland,asymptomatic,160.000000,286.0,False,lv hypertrophy,108.000000,True,1.500000,3.0,normal,2,>60,High,1
2,3,67,Male,Cleveland,asymptomatic,120.000000,229.0,False,lv hypertrophy,129.000000,True,2.600000,2.0,reversable defect,1,>60,Medium,0
3,4,37,Male,Cleveland,non-anginal,130.000000,250.0,False,normal,187.000000,False,3.500000,0.0,normal,0,<40,High,0
4,5,41,Female,Cleveland,atypical angina,130.000000,204.0,False,lv hypertrophy,172.000000,False,1.400000,0.0,normal,0,40-60,Medium,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,916,54,Female,VA Long Beach,asymptomatic,127.000000,333.0,True,st-t abnormality,154.000000,False,0.000000,0.0,normal,1,40-60,High,0
916,917,62,Male,VA Long Beach,typical angina,132.132404,139.0,False,st-t abnormality,137.545665,False,0.878788,0.0,normal,0,>60,Low,0
917,918,55,Male,VA Long Beach,asymptomatic,122.000000,223.0,True,st-t abnormality,100.000000,False,0.000000,0.0,fixed defect,2,40-60,Medium,0
918,919,58,Male,VA Long Beach,asymptomatic,132.132404,385.0,True,lv hypertrophy,137.545665,False,0.878788,0.0,normal,0,40-60,High,0
919,920,62,Male,VA Long Beach,atypical angina,120.000000,254.0,False,lv hypertrophy,93.000000,True,0.000000,0.0,normal,1,>60,High,0

In [19]:
# Encode sex, cp (chest pain type), thal, and AgeGroup
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
for col in ['sex','cp','thal','age_group']:
    df[col] = label_encoder.fit_transform(df[col])

In [20]:
## Normalize numerical features (chol, trestbps, thalach) using MinMaxScaler or StandardScaler.

from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = MinMaxScaler()
df[['chol','trestbps','thalch']] = scaler.fit_transform(df[['chol','trestbps','thalch']])

In [21]:
# BP-Chol Interaction: Create a new feature by multiplying trestbps and chol.

df['BP-Chol_Interaction'] = df['trestbps'] * df['chol']

In [22]:
# Exercise-Induced Angina Risk: Create a binary feature to indicate risk based on exang and thalach.

df['Exercise_Angina_Risk'] = ((df['exang'] == 1) & (df['thalch'] < 100)).astype(int)

In [23]:
df.dtypes

id                        int64
age                       int64
sex                       int64
dataset                  object
cp                        int64
trestbps                float64
chol                    float64
fbs                        bool
restecg                  object
thalch                  float64
exang                      bool
oldpeak                 float64
ca                      float64
thal                      int64
num                       int64
age_group                 int64
chol_types               object
IsRisk                    int64
BP-Chol_Interaction     float64
Exercise_Angina_Risk      int64
dtype: object

In [24]:
# Perform feature selection by evaluating feature importance using a basic model
# (optional).
# Drop redundant or less useful features (e.g., columns with low variance or highly
# correlated with each other).

In [25]:
df.head(5)

# Note: Some columns like 'dataset', 'fbs', 'restecg', 'exang', 'chol_types' are not yet encoded,so we will encode them as well.

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,ca,thal,num,age_group,chol_types,IsRisk,BP-Chol_Interaction,Exercise_Angina_Risk
0,1,63,1,Cleveland,3,0.725,0.386401,True,lv hypertrophy,0.633803,False,2.3,0.0,0,0,2,Medium,0,0.280141,0
1,2,67,1,Cleveland,0,0.800,0.474295,False,lv hypertrophy,0.338028,True,1.5,3.0,1,2,2,High,1,0.379436,1
2,3,67,1,Cleveland,0,0.600,0.379768,False,lv hypertrophy,0.485915,True,2.6,2.0,2,1,2,Medium,0,0.227861,1
3,4,37,1,Cleveland,2,0.650,0.414594,False,normal,0.894366,False,3.5,0.0,1,0,1,High,0,0.269486,0
4,5,41,0,Cleveland,1,0.650,0.338308,False,lv hypertrophy,0.788732,False,1.4,0.0,1,0,0,Medium,0,0.219900,0

In [26]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Encode categorical features using one-hot encoding
df_encoded = pd.get_dummies(df, drop_first=True)

# Assuming 'num' is the target column
X = df_encoded.drop('num', axis=1)  # Features
y = df_encoded['num']               # Target variable

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train a Random Forest model
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Get feature importances and display them
feature_importances = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
}).sort_values(by='Importance', ascending=False)

print("Feature Importance Scores:")
print(feature_importances)

Feature Importance Scores:
                     Feature  Importance
0                         id    0.190689
7                     thalch    0.085243
9                    oldpeak    0.081869
1                        age    0.077878
4                   trestbps    0.070223
14       BP-Chol_Interaction    0.066384
5                       chol    0.062103
3                         cp    0.060972
10                        ca    0.036101
11                      thal    0.034848
16           dataset_Hungary    0.028901
8                      exang    0.027909
15      Exercise_Angina_Risk    0.027555
2                        sex    0.023195
18     dataset_VA Long Beach    0.019176
12                 age_group    0.018993
19            restecg_normal    0.018636
20  restecg_st-t abnormality    0.015552
6                        fbs    0.015407
17       dataset_Switzerland    0.014283
22         chol_types_Medium    0.011809
21            chol_types_Low    0.008693
13                    IsRisk    0.003582